# frozen_string_literal: true

require_relative 'money_gone/config_loader'
require_relative 'money_gone/llm_client'
require_relative 'money_gone/llm_prompts'
require_relative 'money_gone/llm_json_parser'
require_relative 'money_gone/llm_response_normalizer'
require_relative 'money_gone/llm_chat_session'
require_relative 'money_gone/category_label_matcher'
require_relative 'money_gone/stub_llm'
require_relative 'money_gone/importer'
require_relative 'money_gone/models/transaction'
require_relative 'money_gone/normalizer'
require_relative 'money_gone/schema_mapper'
require_relative 'money_gone/transfer_detector'
require_relative 'money_gone/categorizer'
require_relative 'money_gone/pipeline'
require_relative 'money_gone/reporter'
require_relative 'money_gone/cli'
